05 - ASP.NET Core/Capitulo 4/MeuProjetoMVC/MeuProjetoMVC/Models/ErrorViewModel.cs
namespace MeuProjetoMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

05 - ASP.NET Core/Capitulo 4/MeuProjetoMVC/MeuProjetoMVC/Models/Pessoa.cs
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace MeuProjetoMVC.Models
{
    public class Pessoa
    {
        public int Id { get; set; }

        public string Nome { get; set; }

        public string Cpf { get; set; }

        public string Email { get; set; }

        public string Telefone { get; set; }

        public bool EstaValidoParaSalvar(ModelStateDictionary modelState)
        {
            // validando campo nome
            if(string.IsNullOrEmpty(Nome)) 
            {
                modelState.AddModelError(nameof(Nome),"O campo nome é obrigatório");
            }
            else if(Nome.Length > 100)
            {

                modelState.AddModelError(nameof(Nome), "O campo nome deve ter no máximo 100 caracteres");
            }
            // validando campo CPF
            if (string.IsNullOrEmpty(Cpf))
            {
                modelState.AddModelError(nameof(Cpf), "O campo CPF é obrigatório");
            }
            else if (Cpf.Length < 14)
            {

                modelState.AddModelError(nameof(Cpf), "O campo CPF está inválido");
            }
            // validando campo Email
            if(!string.IsNullOrEmpty(Email) && !Email.Contains("@")) 
            {
                modelState.AddModelError(nameof(Email), "O Email está inválido");
            }
            if (string.IsNullOrEmpty(Telefone))
            {
                modelState.AddModelError(nameof(Telefone), "O campo Telefone é obrigatório");
            }
            else if (Telefone.Length < 30)
            {
                modelState.AddModelError(nameof(Telefone), "O campo Telefone está inválido");
            }


            return modelState.IsValid;
        }
    }
}

05 - ASP.NET Core/Capitulo 4/MeuProjetoMVC/MeuProjetoMVC/Controllers/HomeController.cs
using MeuProjetoMVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace MeuProjetoMVC.Controllers
{
    public class HomeController : Controller
    { 
   
        public HomeController()
        {
            
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

05 - ASP.NET Core/Capitulo 4/MeuProjetoMVC/MeuProjetoMVC/Controllers/PessoaController.cs
using MeuProjetoMVC.BancoDeDados.Repositorio;
using MeuProjetoMVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace MeuProjetoMVC.Controllers
{
    public class PessoaController : Controller
    {

        public PessoaRepositorio Repositorio = new PessoaRepositorio();
        // Método chamado ao carregar a pagina pessoa/listagem
        public IActionResult Listagem()
        {

            var pessoas = Repositorio.ObterTodos();
            return View(pessoas);
        }
      
        // Método chamado ao carregar a pagina pessoa/Cadastro
        public IActionResult Cadastro()
        {
            return View();
        }

        // Método chamado ao carregar a pagina pessoa/Edição/Id
        public IActionResult Edicao(int id)
        {            
            var pessoa = Repositorio.ObterporId(id);
            return View(pessoa);
        }

        public IActionResult Adicionar(Pessoa pessoa)
        {

            if (pessoa.EstaValidoParaSalvar(ModelState))
            {
                // adicionar a pessoa na lista
                Repositorio.Adicionar(pessoa);
                return RedirectToAction("Listagem");
            }
            else
            {
                // quando ha algum erro de validação
                return View("Cadastro", pessoa);
            }
        }

        public IActionResult Editar(Pessoa pessoa)
        {
            if (pessoa.EstaValidoParaSalvar(ModelState))
            {
               Repositorio.Atualizar(pessoa);

                return RedirectToAction("Listagem");
            }
            return View("Edicao", pessoa);
        }

        public IActionResult Excluir(int id)
        {

            Repositorio.Excluir(id);
            return RedirectToAction("Listagem");

        }


    }
}

05 - ASP.NET Core/Capitulo 4/MeuProjetoMVC/MeuProjetoMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

05 - ASP.NET Core/Capitulo 4/MeuProjetoMVC/MeuProjetoMVC/Views/Pessoa/Cadastro.cshtml
@model Pessoa

<div class="container mt-4">
    <h2 style="text-align: center;">Cadastro de pessoa</h2>

    @using (Html.BeginForm("Adicionar", "Pessoa", FormMethod.Post, new { @class = "form" }))
    {
        <div class="row">
            <div class="col-sm-12 col-md-12 col-lg-12 form-group">
                @Html.Label("Nome")
                @Html.TextBoxFor(m => m.Nome, new {
            @class = "form-control",
            placeholder = "Digite um nome"
            })
                <span style="color: red;">@Html.ValidationMessageFor(m => m.Nome)</span>

            </div>
            <div class="col-sm-12 col-md-12 col-lg-12 form-group">
                @Html.Label("CPF")
                @Html.TextBoxFor(m => m.Cpf, new {
            @class = "form-control",
            placeholder = "Digite um CPF"
            })
                <span style="color: red;">@Html.ValidationMessageFor(m => m.Cpf)</span>
            </div>
            <div class="col-sm-12 col-md-12 col-lg-12 form-group">
                @Html.Label("E-mail")
                @Html.TextBoxFor(m => m.Email, new {
            @class = "form-control",
            placeholder = "Digite um E-mail"
            })
                <span style="color: red;">@Html.ValidationMessageFor(m => m.Email)</span>
            </div>

             <div class="col-sm-12 col-md-12 col-lg-12 form-group">
                @Html.Label("Telefone")
                @Html.TextBoxFor(m => m.Telefone, new {
            @class = "form-control",
            placeholder = "Digite um Telefone"
            })
                <span style="color: red;">@Html.ValidationMessageFor(m => m.Telefone)</span>
            </div>
        </div>

        <div class="d-flex justify-content-between" style="margin-top: 10px">
            <a href="/Pessoa/Listagem" class="btn btn-primary float-left">Voltar</a>
            <button type="submit" class="btn btn-success float-right">Adicionar</button>
        </div>

    }

</div>

05 - ASP.NET Core/Capitulo 4/MeuProjetoMVC/MeuProjetoMVC/Views/Pessoa/Edicao.cshtml
@model Pessoa

<div class="container mt-4">
    <h2 style="text-align: center;">Edição de pessoa</h2>

    @using (Html.BeginForm("Editar", "Pessoa", FormMethod.Post, new { @class = "form" }))
    {
        <div class="row">
            <div class="col-sm-12 col-md-12 col-lg-12 form-group">
                @Html.Label("Id")
                @Html.TextBoxFor(m => m.Id, new {
            @class = "form-control",
            @readonly = "readonly"
            })
                <span style="color: red;">@Html.ValidationMessageFor(m => m.Id)</span>

            </div>
            <div class="col-sm-12 col-md-12 col-lg-12 form-group">
                @Html.Label("Nome")
                @Html.TextBoxFor(m => m.Nome, new {
            @class = "form-control",
            placeholder = "Digite um nome"
            })
                <span style="color: red;">@Html.ValidationMessageFor(m => m.Nome)</span>

            </div>
            <div class="col-sm-12 col-md-12 col-lg-12 form-group">
                @Html.Label("CPF")
                @Html.TextBoxFor(m => m.Cpf, new {
            @class = "form-control",
            placeholder = "Digite um CPF"
            })
                <span style="color: red;">@Html.ValidationMessageFor(m => m.Cpf)</span>
            </div>
            <div class="col-sm-12 col-md-12 col-lg-12 form-group">
                @Html.Label("E-mail")
                @Html.TextBoxFor(m => m.Email, new {
            @class = "form-control",
            placeholder = "Digite um E-mail"
            })
                <span style="color: red;">@Html.ValidationMessageFor(m => m.Email)</span>
            </div>

                <div class="col-sm-12 col-md-12 col-lg-12 form-group">
                @Html.Label("Telefone")
                @Html.TextBoxFor(m => m.Telefone, new {
            @class = "form-control",
            placeholder = "Digite um Telefone"
            })
                    <span style="color: red;">@Html.ValidationMessageFor(m => m.Telefone)</span>
                </div>
        </div>

        <div class="d-flex justify-content-between" style="margin-top: 10px">
            <a href="/Pessoa/Listagem" class="btn btn-primary float-left">Voltar</a>
            <button type="submit" class="btn btn-success float-right">Atualizar</button>
        </div>

    }

</div>

05 - ASP.NET Core/Capitulo 4/MeuProjetoMVC/MeuProjetoMVC/Views/Pessoa/Listagem.cshtml
<div class="container mt-4">
    <h2 style="text-align: center;">Listagem de pessoas</h2>

    <!-- Botão de Adicionar Novo Registro -->
    <a href="/Pessoa/Cadastro" class="btn btn-success">
        <i class="fa fa-plus"></i> Adicionar Novo Registro
    </a>

    <table class="table">
        <thead>
            <tr>
                <th>Ações</th>
                <th>ID</th>
                <th>Nome</th>
                <th>CPF</th>
                <th>E-mail</th>
                <th>Telefone</th>
            </tr>
        </thead>
        <tbody>
            <!-- Loop pelos registros -->
            @foreach (var registro in Model)
            {
                <tr>
                    <td>
                        <!-- Botão de Edição -->
                        <a class="btn btn-primary btn-sm" href="/Pessoa/Edicao/@registro.Id">
                            <i class="fa fa-edit"></i> Editar
                        </a>

                        <!-- Botão de Exclusão -->
                        <a class="btn btn-danger btn-sm" href="/Pessoa/Excluir/@registro.Id">
                            <i class="fa fa-trash"></i> Excluir
                        </a>
                    </td>
                    <td>@registro.Id</td>
                    <td>@registro.Nome</td>
                    <td>@registro.Cpf</td>
                    <td>@registro.Email</td>
                    <td>@registro.Telefone</td>
                </tr>
            }
        </tbody>
    </table>
</div>

05 - ASP.NET Core/Capitulo 4/MeuProjetoMVC/MeuProjetoMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MeuProjetoMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MeuProjetoMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Meu Projeto</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pessoa" asp-action="Listagem">Listagem de Pessoa</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MeuProjetoMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>